#!/usr/bin/env python3
"""Write base64-encoded dev cloud credentials into a generated plist resource."""

import base64
import os
import plistlib
import sys


MAPPING = {
    "TencentAppIDB64": "MASHANGXIE_DEV_TENCENT_APP_ID",
    "TencentSecretIDB64": "MASHANGXIE_DEV_TENCENT_SECRET_ID",
    "TencentSecretKeyB64": "MASHANGXIE_DEV_TENCENT_SECRET_KEY",
    "AliyunAPIKeyB64": "MASHANGXIE_DEV_ALIYUN_API_KEY",
    "VolcengineAppIDB64": "MASHANGXIE_DEV_VOLCENGINE_APP_ID",
    "VolcengineAccessTokenB64": "MASHANGXIE_DEV_VOLCENGINE_ACCESS_TOKEN",
    "VolcengineSecretKeyB64": "MASHANGXIE_DEV_VOLCENGINE_SECRET_KEY",
}


def encode(value: str) -> str:
    if not value:
        return ""
    return base64.urlsafe_b64encode(value.encode("utf-8")).decode("ascii")


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: write-dev-cloud-resource.py <output.plist>", file=sys.stderr)
        return 2

    output_path = sys.argv[1]
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # The Makefile invokes this script with every MASHANGXIE_DEV_* key present,
    # even when values are intentionally empty. Xcode's post-build phase may run
    # later without those environment variables at all; in that case, preserve the
    # resource generated by Makefile instead of silently overwriting it with blanks.
    has_explicit_environment = any(env_key in os.environ for env_key in MAPPING.values())
    if not has_explicit_environment and os.path.exists(output_path):
        return 0

    payload = {
        build_key: encode(os.environ.get(env_key, ""))
        for build_key, env_key in MAPPING.items()
    }
    with open(output_path, "wb") as handle:
        plistlib.dump(payload, handle, sort_keys=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
