// DictusCore/Sources/DictusCore/Languages/LanguageProfile.swift
// Pure data describing the per-language inputs used by the autocorrect pipeline.
import Foundation

/// Pure-data per-language profile consumed by autocorrect helpers.
///
/// One profile per supported language, declared in `Languages/<Lang>.swift`.
/// The struct holds *only data* — no algorithms. Algorithms live in
/// `TextCorrection/` and read profiles via `SupportedLanguage.profile`.
///
/// WHY pure data:
/// Separating per-language data from the algorithm makes the algorithm testable
/// in isolation (no bridge dependency) and adding a new language a matter of
/// authoring one new file. See ADR 0001 for the policy on what populates these
/// fields on first ship vs. post-launch.
public struct LanguageProfile: Sendable {
    /// BCP-47 short code (e.g. "fr", "en", "es", "de"). Matches `SupportedLanguage.rawValue`.
    public let code: String

    /// Localized display name shown in the settings picker (e.g. "Français").
    public let displayName: String

    /// Two-letter uppercase code shown on the keyboard toolbar language switcher.
    public let shortCode: String

    /// Default keyboard layout for this language (AZERTY for French, QWERTY for others).
    public let defaultLayout: LayoutType

    /// Spacebar label in this language's convention (e.g. "espace", "space", "Leertaste").
    public let spaceName: String

    /// Return key label in this language's convention (e.g. "retour", "return", "Eingabe").
    public let returnName: String

    /// Hard-coded must-correct map: lowercase input → forced correction.
    /// Used for words that are *never* valid in this language without their accent
    /// or contraction (e.g. French `ca` → `ça`). Empty for languages onboarded
    /// without native-speaker curation. See ADR 0001.
    public let overrides: [String: String]

    /// Accent variants generated by `AccentExpander` when a typed word is missing
    /// from the dictionary. Keyed by base letter, value is the list of accents
    /// the algorithm should try at that position.
    public let accentMap: [Character: [Character]]

    /// Apostrophe contraction prefixes used by `ContractionExpander`
    /// (e.g. French `["l'", "d'", "qu'"]`). Each prefix already includes the
    /// apostrophe. Empty for languages without contractions (English, Spanish).
    public let contractionPrefixes: [String]

    /// Length-changing substring substitutions tried by `AccentExpander` when a
    /// typed word isn't a stronger match in the dictionary. Each rule is
    /// `(from, to)` where `from` is the substring to find and `to` is its
    /// replacement. The German `("ss", "ß")` rule lets users typing on a US
    /// keyboard still reach `straße`/`weiß`/`groß` without long-pressing `s`.
    /// Empty for languages without length-changing collapses.
    public let collapseRules: [(from: String, to: String)]

    public init(
        code: String,
        displayName: String,
        shortCode: String,
        defaultLayout: LayoutType,
        spaceName: String,
        returnName: String,
        overrides: [String: String],
        accentMap: [Character: [Character]],
        contractionPrefixes: [String],
        collapseRules: [(from: String, to: String)] = []
    ) {
        self.code = code
        self.displayName = displayName
        self.shortCode = shortCode
        self.defaultLayout = defaultLayout
        self.spaceName = spaceName
        self.returnName = returnName
        self.overrides = overrides
        self.accentMap = accentMap
        self.contractionPrefixes = contractionPrefixes
        self.collapseRules = collapseRules
    }
}

extension SupportedLanguage {
    /// The data profile for this language. Used by the autocorrect helpers in
    /// `TextCorrection/` and (eventually) by the keyboard layout/picker code.
    public var profile: LanguageProfile {
        switch self {
        case .english: return englishProfile
        }
    }
}
