import AppKit

extension NSPasteboard.PasteboardType {
    static let voxFlowInternalMarker = NSPasteboard.PasteboardType("com.voxflow.pasteboard.internal")

    // Adapted from Maccy NSPasteboard.PasteboardType+Types.swift (MIT):
    // https://github.com/p0deje/Maccy
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")
    static let modified = NSPasteboard.PasteboardType("x.nspasteboard.ModifiedType")
    static let universalClipboard = NSPasteboard.PasteboardType("com.apple.is-remote-clipboard")

    static let microsoftObjectLink = NSPasteboard.PasteboardType("com.microsoft.ObjectLink")
    static let microsoftLinkSource = NSPasteboard.PasteboardType("com.microsoft.Link-Source")
    static let microsoftOleSourcePrefix = "com.microsoft.ole.source."

    static let linkPresentationMetadata = NSPasteboard.PasteboardType("com.apple.linkpresentation.metadata")
    static let customWebKitPasteboardData = NSPasteboard.PasteboardType("com.apple.WebKit.custom-pasteboard-data")
    static let customChromiumWebData = NSPasteboard.PasteboardType("org.chromium.web-custom-data")
    static let chromiumSourceURL = NSPasteboard.PasteboardType("org.chromium.source-url")
    static let chromiumSourceToken = NSPasteboard.PasteboardType("org.chromium.internal.source-rfh-token")
    static let notesRichText = NSPasteboard.PasteboardType("com.apple.notes.richtext")
}

enum PasteboardTypeCatalog {
    static let supportedTypes: Set<NSPasteboard.PasteboardType> = [
        .fileURL,
        .html,
        .png,
        .rtf,
        .string,
        .tiff,
    ]

    static let technicalMarkerTypes: Set<NSPasteboard.PasteboardType> = [
        .autoGenerated,
        .concealed,
        .transient,
        .voxFlowInternalMarker,
    ]

    static let transientHashIgnoredTypes: Set<NSPasteboard.PasteboardType> = [
        .modified,
        .linkPresentationMetadata,
        .source,
        .customWebKitPasteboardData,
        .customChromiumWebData,
        .chromiumSourceURL,
        .chromiumSourceToken,
        .notesRichText,
        .voxFlowInternalMarker,
    ]
}
